# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/media_import/pathlike/media_entries.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder # type: ignore
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-src/media_import/pathlike/media_entries.proto\"\xac\x01\n\x0cMediaEntries\x12)\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x18.MediaEntries.MediaEntry\x1aq\n\nMediaEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\x0c\n\x04sha1\x18\x03 \x01(\x0c\x12!\n\x13legacy_zip_filename\x18\xff\x01 \x01(\rH\x00\x88\x01\x01\x42\x16\n\x14_legacy_zip_filenameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.media_import.pathlike.media_entries_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False: # type: ignore

  DESCRIPTOR._options = None
  _globals['_MEDIAENTRIES']._serialized_start=50
  _globals['_MEDIAENTRIES']._serialized_end=222
  _globals['_MEDIAENTRIES_MEDIAENTRY']._serialized_start=109
  _globals['_MEDIAENTRIES_MEDIAENTRY']._serialized_end=222
# @@protoc_insertion_point(module_scope)
