name: checks
 
on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
         submodules: recursive

      - name: Install Python libraries
        run: python -m pip install aqt mypy pyqt5-stubs types-requests types-simplejson pycryptodome

      - name: Run mypy
        run: python -m mypy ./src/addon